---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: ''
    type: text
  - name: TEST_URL
    value: ''
    type: text
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: text-to-speech-nodejs-with-saucelabs
    script: |-
      #!/bin/bash
      cf push "${CF_APP}"

      export CF_APP_NAME="$CF_APP"
      URL=$(cf app $CF_APP | grep 'urls:' | awk '{print $2}' | cut -d '*' -f 2)
      export TEST_URL="https://$URL"

      # View logs
      #cf logs "${CF_APP}" --recent
